### ISSUE TITLE
Still using my personal Google Analytics

### ISSUE THREAD

**Issue by BenEmdon** [daneshbadlani/daneshbadlani.github.io#1]
👋 Hey, looks like your site is using my personal google analytics 😄 Not sure you'd want to keep it:
https://github.com/daneshbadlani/daneshbadlani.github.io/blob/1753fc5edebb0a903c0a5abbbd44e045e0567402/index.html#L7-L15

**Comment by daneshbadlani** [comment]
Hey Ben! Thanks for pointing that out. I have fixed that. Still working on making more changes though!
